version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clonello-network

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: users
      SERVICE_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - clonello-network

  mongo-board:
    image: mongo:5.0
    container_name: mongo-board
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: board_service_db
    volumes:
      - mongo_board_data:/data/db
    networks:
      - clonello-network

  board-service:
    build:
      context: .
      dockerfile: ./services/board-service/Dockerfile
    volumes:
      - ./proto:/proto
    container_name: board-service
    environment:
      DB_HOST: mongo-board
      DB_PORT: 27017
      DB_NAME: board_service_db
      MONGO_USER: root
      MONGO_PASSWORD: secret
      SERVICE_PORT: 8081
    ports:
      - "8081:8081"
      - "50051:50051"
    depends_on:
      - mongo-board
    networks:
      - clonello-network

  mongo-list:
    image: mongo:5.0
    container_name: mongo-list
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: list_service_db
    volumes:
      - mongo_list_data:/data/db
    networks:
      - clonello-network

  list-service:
    build:
      context: .
      dockerfile: ./services/list-service/Dockerfile
    container_name: list-service
    environment:
      DB_HOST: mongo-list
      DB_PORT: 27017
      DB_NAME: list_service_db
      MONGO_USER: root
      MONGO_PASSWORD: secret
      SERVICE_PORT: 50052
      GRPC_BOARD_SERVICE: board-service:50051
    ports:
      - "50052:50052"
    depends_on:
      - mongo-list
      - board-service
    networks:
      - clonello-network

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    environment:
      USER_SERVICE_URL: user-service:8080
      BOARD_SERVICE_URL: board-service:50051
      LIST_SERVICE_URL: list-service:50052
    ports:
      - "8082:8082"
    depends_on:
      - user-service
      - board-service
      - list-service
    networks:
      - clonello-network

networks:
  clonello-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_board_data:
  mongo_list_data:
