version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clonello-network

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: users
      SERVICE_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - clonello-network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: board_service_db
    volumes:
      - mongo_data:/data/db
    networks:
      - clonello-network

  board-service:
    build:
      context: ./services/board-service
      dockerfile: Dockerfile
    container_name: board-service
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: board_service_db
      MONGO_USER: root
      MONGO_PASSWORD: secret
      SERVICE_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - clonello-network

networks:
  clonello-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
